version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - '${HOME}/Documents/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER:-admin}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
