version: '3.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - '${HOME}/Documents/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER:-admin}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   RABBITMQ_DEFAULT_USER: guest
    #   RABBITMQ_DEFAULT_PASS: guest
  # login:
  #   image: sudokus/login
  #   build:
  #     context: .
  #     dockerfile: docker/users
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  #   environment:
  #     MONGODB_USER: '${MONGODB_USER:-admin}'
  #     MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  #     MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
  #     RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
  # startSudoku:
  #   image: sudokus/start
  #   build:
  #     context: .
  #     dockerfile: docker/startSudoku
  #   ports:
  #     - 8082:8081
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  #   restart: on-failure
  #   environment:
  #     MONGODB_USER: '${MONGODB_USER:-admin}'
  #     MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  #     MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
  #     RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
  # generateSudoku:
  #   image: sudokus/generate
  #   build:
  #     context: .
  #     dockerfile: docker/generateSudoku
  #   ports:
  #     - 8083:8081
  #   depends_on:
  #     - mongodb
  #     - rabbitmq
  #   restart: on-failure
  #   environment:
  #     MONGODB_USER: '${MONGODB_USER:-admin}'
  #     MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  #     MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
  #     RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
