version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - '${HOME}/Documents/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER:-admin}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD:-admin}'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  login:
    image: login-image
    build:
      dockerfile: docker/users
    ports:
      - 8081:8081
    environment:
      MONGODB_USER: '${MONGODB_USER:-admin}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
      MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
      RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
  startSudoku:
    image: start-sudoku-image
    build:
      dockerfile: docker/startSudoku
    ports:
      - 8081:8081
    environment:
      MONGODB_USER: '${MONGODB_USER:-admin}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
      MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
      RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
  generateSudoku:
    image: generate-sudoku-image
    build:
      dockerfile: docker/generateSudoku
    ports:
      - 8081:8081
    environment:
      MONGODB_USER: '${MONGODB_USER:-admin}'
      MONGODB_PASSWORD: '${MONGODB_PASSWORD:-admin}'
      MONGODB_CONNECTION: '${MONGODB_CONNECTION:-localhost}'
      RABBITMQ_CONNECTION: '${RABBITMQ_CONNECTION:-localhost}'
