apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Deployment
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      template:
        metadata:
          name: mongo
          app:
            name: mongo
        spec:
          containers:
            - image: mongo:latest
              name: mongo
              ports:
                - name: mongo
                  containerPort: 27017
                  volumeMounts:
                    - name: mongo-storage
                      mountPath: /data/db
          volumes:
            - name: mongo-storage
              persistentVolumeClaim:
                claimName: mongo-storage
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo
      labels:
        app: mongo
        name: mongo
    spec:
      ports:
        - port: 27017
          targetPort: 27017
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo-storage
      labels:
        app: mongo
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
