FROM registry.access.redhat.com/ubi9/go-toolset:latest
WORKDIR /app
USER root

COPY ./API ./
RUN go mod download

RUN mkdir bin
RUN go build -o /app/bin/users ./users
RUN go build -o /app/bin/startSudoku ./startSudoku
RUN go build -o /app/bin/generateSudoku ./generateSudoku

EXPOSE 8081