---
kind: Service
apiVersion: v1
metadata:
  name: generate-sudoku
  annotations:
    prometheus.io/scrape: true
  labels:
    app: generate-sudoku
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: generate-sudoku
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: generate-sudoku
  labels:
    app: generate-sudoku
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: generate-sudoku
  labels:
    app: generate-sudoku
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/Cyberduc-k/Cloud2.git"
      ref: main
    contextDir: .
  strategy:
    dockerStrategy:
      dockerfilePath: docker/generateSudoku
  output:
    to:
      kind: ImageStreamTag
      name: generate-sudoku:latest
  triggers:
    - type: ConfigChange
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: generate-sudoku
  labels:
    app: generate-sudoku
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - generate-sudoku
        from:
          kind: ImageStreamTag
          name: generate-sudoku:latest
  replicas: 1
  selector:
    matchLabels:
      app: generate-sudoku
  template:
    metadata:
      name: generate-sudoku
      labels:
        app: generate-sudoku
    spec:
      containers:
        - name: generate-sudoku
          image: generate-sudoku:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mongodb
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mongodb
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 1
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: generate-sudoku
  labels:
    app: generate-sudoku
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: generate-sudoku
  targetCPUUtilizationPercentage: 70
